In [1]:
import numpy as np
from hmmlearn import hmm
# 设定隐藏状态的集合 
states = ["box 1", "box 2", "box3"] 
n_states = len(states) 
# 设定观察状态的集合 
observations = ["red", "white"] 
n_observations = len(observations) 
# 设定初始状态分布 
start_probability = np.array([0.2, 0.4, 0.4])
# 设定状态转移概率分布矩阵 
transition_probability = np.array([ [0.5, 0.2, 0.3], [0.3, 0.5, 0.2], [0.2, 0.3, 0.5]])
# 设定观测状态概率矩阵 
emission_probability = np.array([ [0.5, 0.5], [0.4, 0.6], [0.7, 0.3] ])

In [4]:
# 设定模型参数 
model = hmm.MultinomialHMM(n_components=n_states) 
model.startprob_=start_probability 
# 初始状态分布 
model.transmat_=transition_probability 
# 状态转移概率分布矩阵 
model.emissionprob_=emission_probability 
# 观测状态概率矩阵
seen = np.array([[0,1,0]]).T 
# 设定观测序列 
box = model.predict(seen) 
# print("球的观测顺序为：\n", ", ".join(map(lambda x: observations[x], seen.flatten()))) 
# # 注意：需要使⽤flatten⽅法，把seen从⼆维变成⼀维 
# print("最可能的隐藏状态序列为:\n"， ", ".join(map(lambda x: states[x], box)))
print(model.score(seen))
box

-2.038545309915233


array([2, 2, 2])

In [95]:
import numpy as np
# 前向算法
class ForwardHmm:
    def __init__(self,n_components,observations):
        self.n_components=n_components
        self.observations=observations
    def fit(self,start_probability,transition_probability,emission_probability):
        self.start_probability=start_probability
        self.transition_probability=transition_probability
        self.emission_probability=emission_probability
    def predict(self,test_data):
        t=len(test_data)
        if t<1:
            print("t<1")
            return
        target_type=test_data[0]
        target_index=self.observations.index(target_type)
        
        self.start_probability=self.start_probability*self.emission_probability[:,target_index]
        if t==1:
            return np.sum(self.start_probability)
        for i in range(t-1):
            target_type=test_data[i+1]
            target_index=self.observations.index(target_type)
            pi=[]
            for i in range(len(self.transition_probability)):
                pi.append(self.transition_probability[:,i].dot(self.start_probability)*self.emission_probability[:,target_index][i])
            self.start_probability=np.array(pi)
            print(self.start_probability)
        return np.sum(self.start_probability)
                
# 设定隐藏状态的集合 
states = ["box 1", "box 2", "box3"] 
n_states = len(states) 
# 设定观察状态的集合 
observations = ["red", "white"] 
n_observations = len(observations)
# 设定初始状态分布 
start_probability = np.array([0.2, 0.4, 0.4])
# 设定状态转移概率分布矩阵 
transition_probability = np.array([ [0.5, 0.2, 0.3], [0.3, 0.5, 0.2], [0.2, 0.3, 0.5]])
# 设定观测状态概率矩阵 
emission_probability = np.array([ [0.5, 0.5], [0.4, 0.6], [0.7, 0.3] ])

my_hmm=ForwardHmm(states,observations)
my_hmm.fit(start_probability,transition_probability,emission_probability)
test_data=["red", "white","red"]
my_hmm.predict(test_data)

[0.077  0.1104 0.0606]
[0.04187  0.035512 0.052836]


0.130218

In [38]:
len(transition_probability)

3

--------------------Load Data------------------------
<class 'numpy.matrix'> 199 <class 'numpy.matrix'> 199
<class 'numpy.matrix'> 4864 <class 'numpy.matrix'> 4864
--------------------Parameter Setup------------------
-------------------Save LSSVM Model-----------------
------------------Predict Result------------------ -
-------------------Average Error------------------ -
-------------------Average Error------------------ - 18898.045648761607


matrix([[1313],
        [ 678],
        [3464],
        ...,
        [3092],
        [3772],
        [ 860]], dtype=int64)

4864