 理论来自 https://www.cnblogs.com/zzqingwenn/p/10874522.html

In [184]:
import numpy as np
from sklearn.metrics import r2_score
import random
import matplotlib.pyplot as plt
import numpy as np
from numpy import *
import itertools
def sample_generate(K, n, x_max, noise):
    X = [[int(x_max*random.random()) for j in range(len(K)-1)]+[1] for i in range(n)]
    Y = [[sum([K[j]*X[i][j] for j in range(len(K))])+int(noise*random.random())] for i in range(n)]
    return [X,Y]
 
#L2正则（岭回归）
def w_ridge(X,Y):
    XTX = np.dot(X.T, X)
    c = 1e-5
    if np.linalg.det(XTX) == 0:
        XTX = XTX + c*np.eye(len*(XTX))
    #逆
    #w = np.dot(np.linalg.inv(XTX), np.dot(X.T, Y))
    #广义逆
    w = np.dot(np.linalg.pinv(XTX), np.dot(X.T, Y))
    return w
 
def show(K,w):
    print("原始参数："+str(K))
    w = w.tolist()
    for i in range(len(w)):
        w[i] = w[i][0]
    print("回归参数："+str(w))
 
def lost_lasso(X, Y, w, lambd):
    return ((Y-X*w).T*(Y-X*w))[0,0] + lambd*sum([abs(w[i,0]) for i in range(w.shape[0])])
 
#L1正则（lasson）   
def w_lasson(X, Y, lambd=0.2, threshould=1e-5):
    
    m,n = X.shape
    w = np.matrix(np.ones((n,1)))
    lost = lost_lasso(X, Y, w, lambd)
    print(lost)
    
    while True:
        for i in range(n):
            a = (X[:,i].T*X[:,i])[0,0]
            dw = np.matrix(np.zeros((n,1)))
            dw[i,0] = w[i,0]
            b0 = -2*(X.T*(Y-X*(w-dw)))[i,0]
            if b0 <= -lambd:
                w[i,0] = (-lambd-b0)/a/2
            elif b0 >= lambd:
                w[i,0] = (lambd-b0)/a/2
            else:
                w[i,0] = 0
        lost1 = lost_lasso(X, Y, w, lambd)
        if abs(lost-lost1) <= threshould:
            break
        lost = lost1
    return w
    
K = [3,4,5,6,7,8,9]
sample =  sample_generate(K, 100, 100, 2)
X = np.matrix(sample[0])
Y = np.matrix(sample[1])
#岭回归
w = w_ridge(X,Y)
show(K,w)
w1 = w_lasson(X, Y)
show(K,w1)

原始参数：[3, 4, 5, 6, 7, 8, 9]
回归参数：[3.0022224267851243, 4.003982844814033, 4.999790289287326, 6.0010168908097254, 7.002295331396681, 7.999518098171848, 9.0638499681736]
192726263.4
原始参数：[3, 4, 5, 6, 7, 8, 9]
回归参数：[3.0022580829619865, 4.004062501118288, 4.999828236348335, 6.001068399464604, 7.00236396824823, 7.999630655116901, 9.043520154423078]


In [181]:

class Lasso:
    def __init__(self,lambd=0.2,max_iter=1000,threshould=1e-5):
        self.max_iter=max_iter
        self.lambd=lambd
        self.threshould=threshould
    def fit(self,trainX,trainY):
        n=trainX.shape[0]
        p=trainX.shape[1]
        w=np.ones(p)
        print(self.loss_func(trainX,trainY,w))
        for iter_ in range(self.max_iter):
            for i in range(p):
                pass
        pass
    # 损失函数
    def loss_func(self,X,Y,w):
        return (np.dot((Y - np.dot(X,w)).T,(Y - np.dot(X,w)))+np.sum(abs(w))*self.lambd)/len(Y)



In [31]:
def sample_generate(K, n, x_max, noise):
    X = [[int(x_max*random.random()) for j in range(len(K)-1)]+[1] for i in range(n)]
    Y = [[sum([K[j]*X[i][j] for j in range(len(K))])+int(noise*random.random())] for i in range(n)]
    return [X,Y]

In [129]:
K = [3,4,5,6,7,8,9]
sample =  sample_generate(K, 100, 100, 2)
X = np.matrix(sample[0])
Y = np.matrix(sample[1])
lasso= Lasso()
lasso.fit(X,Y)

19390386820.014


In [80]:
from numpy import *
np.sum(np.array(((Y-X*w).T*(Y-X*w))))

26.89896139517198

In [91]:
np.sum(((Y-X*w).T*(Y-X*w)))+np.sum(abs(w))

68.82376807985838

In [119]:
(np.dot((Y-np.dot(X,w)).T,(Y-np.dot(X,w))))

matrix([[26.45823317]])

In [131]:
np.dot(X,w)

matrix([[1263.7109751 ],
        [1367.40936722],
        [ 903.2842664 ],
        [2192.55197591],
        [1743.61481187],
        [1743.46209254],
        [ 868.39793116],
        [2379.48821195],
        [ 821.51795777],
        [1537.72735708],
        [1740.52398183],
        [1914.75329458],
        [2297.54383966],
        [1547.34208792],
        [1379.64063785],
        [ 779.38782495],
        [2165.53143757],
        [1372.47120584],
        [1339.87515447],
        [1123.61600759],
        [1395.4478434 ],
        [1657.44641649],
        [1554.44483954],
        [1639.85583082],
        [2115.64766041],
        [1698.62767804],
        [1823.5120711 ],
        [1800.43135444],
        [1775.60937313],
        [1404.41256797],
        [1887.86428829],
        [1915.49661294],
        [2075.55700561],
        [ 923.47350249],
        [1653.31015022],
        [1607.59131805],
        [1777.21107836],
        [1829.56516862],
        [1585.41209674],
        [1391.45084454],


In [137]:
(Y-np.dot(X,w)).T.shape

(1, 100)

In [169]:
w=np.ones((X.shape[1],1))
w

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [161]:
np.dot((Y.T-np.dot(X,w)),(Y.T-np.dot(X,w)).T)

matrix([[ 16693706.01158397,  14172853.80889338,  16827899.48643102, ...,
          19499585.86447198,  14691820.169955  ,  17210540.98586935],
        [ 14172853.80889338,  71223731.45098773,  11135842.94975011, ...,
         -49328650.95789723,  59478700.80869605,   2476059.82484345],
        [ 16827899.48643102,  11135842.94975011,  17130906.87610178, ...,
          23163545.32109192,  12307663.28282852,  17994907.17162037],
        ...,
        [ 19499585.86447197, -49328650.95789723,  23163545.32109193, ...,
          96110091.9479157 , -35159022.30459192,  33611020.07320078],
        [ 14691820.169955  ,  59478700.80869605,  12307663.28282852, ...,
         -35159022.30459192,  50258452.01998061,   5509438.79966277],
        [ 17210540.98586935,   2476059.82484345,  17994907.17162037, ...,
          33611020.07320078,   5509438.79966277,  20231461.92040063]])

In [150]:
np.dot(X,w).shape

(1, 100)

In [155]:
1.93078565e+08-308833234.0

-115754669.0

In [177]:
np.dot(Y - np.dot(X,w).T,(Y - np.dot(X,w)))

matrix([[1.83910240e+08],
        [7.97144780e+07],
        [1.89302000e+08],
        [1.10312716e+08],
        [8.57802080e+07],
        [1.35384400e+08],
        [1.82157918e+08],
        [1.55738294e+08],
        [2.28661848e+08],
        [1.16782828e+08],
        [1.56007882e+08],
        [1.10043128e+08],
        [1.52503238e+08],
        [2.76513718e+08],
        [2.65460610e+08],
        [3.14795214e+08],
        [1.55603500e+08],
        [1.92132674e+08],
        [2.04533722e+08],
        [1.40102190e+08],
        [2.38367016e+08],
        [1.45628744e+08],
        [7.60750400e+07],
        [1.66252226e+08],
        [1.78922862e+08],
        [2.36345106e+08],
        [2.50633270e+08],
        [2.28527054e+08],
        [1.61399642e+08],
        [1.79866420e+08],
        [1.41854512e+08],
        [2.14104096e+08],
        [1.37136722e+08],
        [2.33514432e+08],
        [1.64230316e+08],
        [1.72722338e+08],
        [4.42636560e+07],
        [1.75553012e+08],
        [1.7

matrix([[1.93246876e+08]])

520612.59999999404