In [3]:
import numpy as np

import matplotlib.pyplot as plt
from sklearn import datasets
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]
X.shape


trainX, testX, trainY, testY = train_test_split(X, y)
print(trainX)

[[5.6600e-02 0.0000e+00 3.4100e+00 ... 1.7800e+01 3.9690e+02 5.5000e+00]
 [2.1038e-01 2.0000e+01 3.3300e+00 ... 1.4900e+01 3.9690e+02 4.8500e+00]
 [2.5387e-01 0.0000e+00 6.9100e+00 ... 1.7900e+01 3.9690e+02 3.0810e+01]
 ...
 [6.7191e-01 0.0000e+00 8.1400e+00 ... 2.1000e+01 3.7688e+02 1.4810e+01]
 [2.8990e-02 4.0000e+01 1.2500e+00 ... 1.9700e+01 3.8985e+02 5.8900e+00]
 [3.6150e-02 8.0000e+01 4.9500e+00 ... 1.9200e+01 3.9690e+02 4.7000e+00]]


In [12]:
import numpy as np
class LinearReg:
    def __init__(self,max_iter=100):
        self.coef=None
        self.intercept=None
        self.theta=None
        self.max_iter=max_iter
    def fit(self,trainX,trainY):
        X_b=np.hstack((np.ones((len(trainX),1)),trainX))
        self.theta=np.zeros((X_b.shape[1]))
        for i in range(self.max_iter):
            pass
        print(self.theta)
        pass
    def predict(self,testX):
        pass
    

In [13]:
lr=LinearReg()
lr.fit(trainX,trainY)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# sklean 线性回归
from sklearn.linear_model import LinearRegression
l=LinearRegression();
l.fit(trainX,trainY)
print(l.coef_)
print(l.intercept_)
l.predict(testX)

[-1.20434656e-01  3.95278299e-02 -2.17215703e-02  4.78452628e-01
 -1.34647468e+01  3.38188799e+00 -2.63055613e-02 -1.31410993e+00
  2.85958387e-01 -1.51849414e-02 -9.27674419e-01  7.72394171e-03
 -3.54183986e-01]
37.53034800866911


array([13.54623616, 23.95708212, 23.54812498, 31.57350337, 20.95120759,
       12.51369292, 18.93266946, 33.15754219, 17.33193563, 22.37362818,
       20.81757993, 28.50858201, 25.03608429, 14.42746993, 19.42265773,
       33.05675133, 23.95521531, 34.62044392, 28.67702129, 23.00018731,
       35.96732687, 20.69547057, 26.73803508, 31.36764328, 31.94599376,
       18.90216608, 13.33788312, 35.65500335, 29.90709706, 16.41698852,
       28.61094685, 10.89032506, 22.20793729, 23.03234264, 14.64439524,
       21.73289762, 22.48545206, 27.38571594, 24.84678264, 19.3855551 ,
       21.81109421, 23.06119805, 30.16250116, 26.5013037 , 25.8821606 ,
       15.06737035,  7.98435731, 25.58870226, 21.64003233, 27.89410761,
       20.39858206, 26.33729058, 23.3463114 , 26.00485109, 16.5305228 ,
       15.44207748, 16.2370134 , 30.87764458, 17.6107402 , 17.72778634,
       32.23914874, 24.4361423 , 17.32339595, 15.91330305, 23.82577199,
       14.79884038, 30.3858727 , 18.74857536, 12.83996226, 35.31